module.exports = {
  name: "nepal",
  usePrefix: false,
  usage: "nepal",
  version: "3.0",
  admin: false,
  cooldown: 3,

  execute: async ({ api, event }) => {
    const { threadID, messageID } = event;

    const links = [
      "https://i.imgur.com/vMmK0BI.jpg",
      "https://i.imgur.com/JkpdSVM.jpg",
      "https://i.imgur.com/5UBhGZl.jpg",
      "https://i.imgur.com/6XKKtFf.jpg",
      "https://i.imgur.com/PmD1Hxv.jpg",
      "https://i.imgur.com/1QfkwzT.jpg",
      "https://i.imgur.com/KBqQhKq.jpg",
      "https://i.imgur.com/5TFN6c7.jpg",
      "https://i.imgur.com/W9eY3Xl.jpg",
      "https://i.imgur.com/onc9ckj.jpg",
      "https://i.imgur.com/ImLuJxV.jpg",
      "https://i.imgur.com/2cvZ2Iy.jpg",
      "https://i.imgur.com/RoD3P7B.jpg",
      "https://i.imgur.com/6DLleP0.jpg",
      "https://i.imgur.com/ANN4wSY.jpg",
      "https://i.imgur.com/1uwSbjg.jpg",
      "https://i.imgur.com/NgNEXw8.jpg",
      "https://i.imgur.com/ls8evPi.jpg",
      "https://i.imgur.com/TkDzvq4.jpg",
      "https://i.imgur.com/R1qSSiH.jpg",
      // 80+ more links below, from public albums & free sources
      "https://i.imgur.com/3ukJSGW.jpg",
      "https://i.imgur.com/gkigHWr.jpg",
      "https://i.imgur.com/qiuaR8e.jpg",
      "https://i.imgur.com/uuYzr14.jpg",
      "https://i.imgur.com/B3RCSYc.jpg",
      "https://i.imgur.com/dfKi8sy.jpg",
      "https://i.imgur.com/g7qtlxN.jpg",
      "https://i.imgur.com/DqjAJC1.jpg",
      "https://i.imgur.com/BJzA4Ew.jpg",
      "https://i.imgur.com/Ulg8z7g.jpg",
      "https://i.imgur.com/a8r5mvx.jpg",
      "https://i.imgur.com/qpz6zOF.jpg",
      "https://i.imgur.com/6hwcP5x.jpg",
      "https://i.imgur.com/KEUO6JN.jpg",
      "https://i.imgur.com/ExQHzKw.jpg",
      "https://i.imgur.com/bOzp3jH.jpg",
      "https://i.imgur.com/MILSGP3.jpg",
      "https://i.imgur.com/F8CgLBg.jpg",
      "https://i.imgur.com/t0ctVvX.jpg",
      "https://i.imgur.com/d8gxIbH.jpg",
      "https://i.imgur.com/8dEKzY1.jpg",
      "https://i.imgur.com/6P8KnJh.jpg",
      "https://i.imgur.com/TJRh5tc.jpg",
      "https://i.imgur.com/qlntJHl.jpg",
      "https://i.imgur.com/JgB5vHG.jpg",
      "https://i.imgur.com/6a0KZ2X.jpg",
      "https://i.imgur.com/vsOpa8g.jpg",
      "https://i.imgur.com/qPtn0Rf.jpg",
      "https://i.imgur.com/OaT4shk.jpg",
      "https://i.imgur.com/GJMXUjl.jpg",
      "https://i.imgur.com/Hx5X3Wb.jpg",
      "https://i.imgur.com/qyEcNPH.jpg",
      "https://i.imgur.com/7XOX7dW.jpg",
      "https://i.imgur.com/kzzOYHf.jpg",
      "https://i.imgur.com/FZ47wFg.jpg",
      "https://i.imgur.com/93HrRMj.jpg",
      "https://i.imgur.com/vV8pHTP.jpg",
      "https://i.imgur.com/XdTQrbO.jpg",
      "https://i.imgur.com/3I9zQqM.jpg",
      "https://i.imgur.com/sr4ZjZc.jpg",
      "https://i.imgur.com/5E7tBjV.jpg",
      "https://i.imgur.com/UFl3KmV.jpg",
      "https://i.imgur.com/zwF1lVP.jpg",
      "https://i.imgur.com/l6iVtFG.jpg",
      "https://i.imgur.com/1DvCkmG.jpg",
      "https://i.imgur.com/Vq58LKc.jpg",
      "https://i.imgur.com/Y67jwzK.jpg",
      "https://i.imgur.com/pChDKri.jpg",
      "https://i.imgur.com/COq0vG1.jpg",
      "https://i.imgur.com/NW0d7tY.jpg",
      "https://i.imgur.com/HEy1OPL.jpg",
      "https://i.imgur.com/0YKYh6f.jpg",
      "https://i.imgur.com/3fjRBax.jpg",
      "https://i.imgur.com/Vq2NVEM.jpg",
      "https://i.imgur.com/cPApznJ.jpg",
      "https://i.imgur.com/hw91gXW.jpg",
      "https://i.imgur.com/3wOxN2H.jpg",
      "https://i.imgur.com/mGQlQtL.jpg",
      "https://i.imgur.com/cTNoT9J.jpg",
      "https://i.imgur.com/g2OlBYs.jpg",
      "https://i.imgur.com/v0yqvZz.jpg",
      "https://i.imgur.com/8IkCrN6.jpg",
      "https://i.imgur.com/ogMcJ2f.jpg",
      "https://i.imgur.com/mQIdI3L.jpg",
      "https://i.imgur.com/X5ybmsh.jpg",
      "https://i.imgur.com/ud6CRXz.jpg",
      "https://i.imgur.com/p1K9q6n.jpg",
      "https://i.imgur.com/H4pWLw9.jpg",
      "https://i.imgur.com/UiEqHcT.jpg",
      "https://i.imgur.com/gkdPl28.jpg",
      "https://i.imgur.com/9xp7sRh.jpg",
      "https://i.imgur.com/QRnEr6N.jpg",
      "https://i.imgur.com/4V7QOPV.jpg",
      "https://i.imgur.com/43by7Bq.jpg",
      "https://i.imgur.com/yHqIEQK.jpg",
      "https://i.imgur.com/kBWgnnG.jpg",
      "https://i.imgur.com/G2YFgVQ.jpg",
      "https://i.imgur.com/p9H7v6E.jpg",
      "https://i.imgur.com/jTkpGxP.jpg",
      "https://i.imgur.com/WLSI7Kt.jpg",
      "https://i.imgur.com/3hPpVay.jpg",
      "https://i.imgur.com/Y6hcZoA.jpg",
      "https://i.imgur.com/DR63cYn.jpg",
      "https://i.imgur.com/F32ZxmE.jpg",
      "https://i.imgur.com/RzUbztM.jpg",
      "https://i.imgur.com/I4oRy7X.jpg",
      "https://i.imgur.com/3TKo5hS.jpg",
      "https://i.imgur.com/UXFqpJo.jpg",
      "https://i.imgur.com/w8CnQHW.jpg",
      "https://i.imgur.com/iyIq8Dj.jpg",
      "https://i.imgur.com/nA6H9bH.jpg",
      "https://i.imgur.com/PC1v7AU.jpg",
      "https://i.imgur.com/H6YRHIm.jpg",
      "https://i.imgur.com/1qgZPeK.jpg",
      "https://i.imgur.com/4b4H73r.jpg",
      "https://i.imgur.com/e81gqUj.jpg",
      "https://i.imgur.com/hW3rtWZ.jpg",
      "https://i.imgur.com/gnrSoTW.jpg"
    ];

    const img = links[Math.floor(Math.random() * links.length)];

    return api.sendMessage({
      body: "🇳🇵 Beautiful Nepal ❤️",
      attachment: await global.utils.getStreamFromURL(img),
      buttons: [
        { type: "postback", label: "🌄 Another View", payload: "NEPAL_AGAIN" }
      ]
    }, threadID, messageID);
  },

  handleEvent: async ({ api, event }) => {
    if (event.body === "NEPAL_AGAIN") {
      return module.exports.execute({ api, event });
    }
  }
};
